controllers:
  resource: ../src/Shared/Infrastructure/Controller/
  type: attribute

kernel:
  resource: ../src/Shared/Infrastructure/Kernel.php
  type: annotation
  
api_refresh_token:
  path: /api/auth/token/refresh

api_login_check:
  path: /api/auth/token/login

users:
  resource: ../src/Users/Infrastructure/Controller/
  type: annotation