controllers:
  resource: ../src/Controller/
  type: attribute

hello:
  path: /hello
  # the controller value has the format 'controller_class::method_name'
  controller: App\Controller\HelloWorldController
