# Чтобы сообщить фреймворку о местонахождении фикстур, нужно определить сервисы для тестового окружения
services:
  App\Tests\Resource\Fixture\:
    resource: '%kernel.project_dir%/tests/Resource/Fixture/*'
    tags:
      - { "name": "doctrine.fixture.orm" }